name: CI tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:

  Run-tests:
    # Prevents from running on forks where no custom runners are available
    if: ${{ github.repository_owner == 'verilog-to-routing' }}

    container: ubuntu:bionic

    runs-on: [self-hosted, Linux, X64]

    strategy:
      fail-fast: false
      matrix:
        include:
          - {test: "vtr_reg_nightly_test1", cores: "8",  options: "",          cmake: ""                                             }
          - {test: "vtr_reg_nightly_test2", cores: "16", options: "",          cmake: ""                                             }
          - {test: "vtr_reg_nightly_test3", cores: "16", options: "",          cmake: ""                                             }
          - {test: "vtr_reg_nightly_test4", cores: "16", options: "",          cmake: ""                                             }
          - {test: "vtr_reg_strong",        cores: "16", options: "",          cmake: "-DVTR_ASSERT_LEVEL=3"                         }
          - {test: "vtr_reg_strong",        cores: "16", options: "-skip_qor", cmake: "-DVTR_ASSERT_LEVEL=3 -DVTR_ENABLE_SANITIZE=ON"}
          - {test: "vtr_reg_yosys",         cores: "16", options: "",          cmake: "-DWITH_YOSYS=ON"                              }
          - {test: "vtr_reg_yosys_odin",    cores: "16", options: "",          cmake: "-DODIN_USE_YOSYS=ON"                          }
          - {test: "odin_tech_strong",      cores: "16", options: "",          cmake: "-DODIN_USE_YOSYS=ON"                          }
          - {test: "odin_reg_strong",       cores: "16", options: "",          cmake: ""                                             }

    env:
      DEBIAN_FRONTEND: "noninteractive"

    steps:

    - uses: actions/checkout@v2

    - name: Setup
      run: stdbuf -i0 -i0 -e0 ./.github/scripts/hostsetup.sh

    - name: Execute test script
      run: stdbuf -i0 -o0 -e0 ./.github/scripts/run-vtr.sh
      env:
        VTR_TEST: ${{ matrix.test }}
        VTR_TEST_OPTIONS: ${{ matrix.options }}
        VTR_CMAKE_PARAMS: ${{ matrix.cmake }}
        NUM_CORES: ${{ matrix.cores }}

    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        path: |
          **/results*.gz
          **/plot_*.svg
          **/qor_results*.tar.gz
